/**:
  ros__parameters:
    # Pulley radii (meters)
    ra: 0.0075
    rb: 0.0025
    rc: 0.0025

    # Tendon moment arm radii (meters)
    # r1: 0.008
    # r3: -0.0045
    # r5: 0.008
    # r7: 0.0045
    # r9: 0.009
    # r11: -0.0075 * 3.5  # ra * Gear_ratio
    
    r1: -0.008
    r3: 0.0045
    r5: -0.008
    r7: -0.0045
    r9: -0.01
    r11: -0.02625  # -ra * Gear_ratio

    # these build the structure matrix, account for signs in this file!!!
      # r11_ , r3_ , r1_ 
      # 0.0  , r7_ , r5_ 
      # 0.0  , 0.0 , r9_

    # Screw axes (space frame), row-major, 4 axes x 6 elements = 24 values
    slist: [
       0.0,  0.0,  1.0,  0.0,    0.0,    0.0,
      -1.0,  0.0,  0.0,  0.0,    0.0,    0.0178,
      -1.0,  0.0,  0.0,  0.0,    0.0,    0.079,
      -1.0,  0.0,  0.0,  0.0,    0.0,    0.1195
    ]

    # Joint limits (rad): [splay/MCP, MCP flex, PIP/DIP flex]
    joint_min: [-0.55, -0.2617994,   -0.0]
    joint_max: [ 0.55,  1.572,  1.572]

    # Home configuration M (SE3), row-major 4x4
    M: [
      1.0, 0.0, 0.0, 0.0,
      # 0.0, 1.0, 0.0, 0.146,
      0.0, 1.0, 0.0, 0.15,
      0.0, 0.0, 1.0, 0.0,
      0.0, 0.0, 0.0, 1.0
    ]

    # 4-bar linkage side lengths (meters): [a, b, c, d]
    four_bar_lengths: [0.00883765, 0.0406, 0.00891536, 0.037799030]

    # Ground height offset relative to finger base (meters)
    relative_gnd_height: -0.25
