/finger_demo:
  ros__parameters:
    # Sinusoidal demo parameters
    sinusoidal:
      repeat: 1
      joint: `
      amp: 0.1
      freq: 10.0
      v_offset: 0.7

    # Chirp demo parameters
    chirp:
      joint: 1
      amp: 0.1
      freq_init: 0.1
      freq_final: 15.0
      time: 8.0
      v_offset: 0.5   # pi/4 rad

    chirp_velocity:
      joint: 1
      vel_amp: 3.0
      freq_init: 1.0
      freq_final: 30.0
      time: 8.0
      start_pos: [0.0, 0.5, 0.0]  # pi/4 rad

    # Linear move demo parameters
    linear:
      repeat: 1
      waypoints: [0.0, 0.0, 0.0,
                  0.0, 0.1, 0.1,
                  0.0, 0.0, 0.0]

    linear_step:
      repeat: 1
      freq: 4.0
      waypoints: [
        0.0, 0.0, 0.0,
        0.0, 1.3, 1.3]


    # Force step demo parameters
    force:
      repeat: 1
      freq: .5
      q_state: [0.0, 0.0, 0.0]
      low: [0.0, 0.0, 1.0]
      high: [0.0, 0.0, 20.0]

    # IK demo parameters
    ik:
      repeat: 1
      waypoints: [0.05, 0.08, -0.1,
                 -0.05, 0.08, -0.1,
                  0.05, 0.08, -0.1]
